# Generated by Django 6.0.4 on 2026-05-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studytask',
            name='category',
            field=models.CharField(default='Coding', max_length=100),
        ),
        migrations.AddField(
            model_name='studytask',
            name='due_date',
            field=models.DateField(default='2026-05-08'),
        ),
        migrations.AddField(
            model_name='studytask',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20),
        ),
    ]
